"""empty message

<<<<<<< HEAD
<<<<<<<< HEAD:migrations/versions/1a8224881521_.py
Revision ID: 1a8224881521
Revises:
Create Date: 2023-11-27 17:28:43.564369
========
Revision ID: 1bd787ee40cf
Revises: 
Create Date: 2023-11-27 19:11:03.475168
>>>>>>>> 761b1e0 (readme push):migrations/versions/1bd787ee40cf_.py
=======
<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
<<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
Revision ID: 6506cb7e81a2
Revises: 
Create Date: 2023-11-27 11:35:31.747436
========
Revision ID: 2cfb087e8c2d
Revises: 
Create Date: 2023-11-22 08:25:31.237377
>>>>>>>> a6fb8e4 (change table name):migrations/versions/2cfb087e8c2d_.py
=======
Revision ID: 1a8224881521
Revises:
Create Date: 2023-11-27 17:28:43.564369
>>>>>>> ec7cf82 (This is dumb):migrations/versions/1a8224881521_.py
>>>>>>> 067e912 (This is dumb)

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD
<<<<<<<< HEAD:migrations/versions/1a8224881521_.py
revision = '1a8224881521'
========
revision = '1bd787ee40cf'
>>>>>>>> 761b1e0 (readme push):migrations/versions/1bd787ee40cf_.py
=======
<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
<<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
revision = '6506cb7e81a2'
========
revision = '2cfb087e8c2d'
>>>>>>>> a6fb8e4 (change table name):migrations/versions/2cfb087e8c2d_.py
=======
revision = '1a8224881521'
>>>>>>> ec7cf82 (This is dumb):migrations/versions/1a8224881521_.py
>>>>>>> 067e912 (This is dumb)
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(length=20000), nullable=True),
    sa.Column('units_available', sa.INTEGER(), nullable=False),
    sa.Column('preview_image', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wishlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cart_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_products',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('order_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('seller_commented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<< HEAD
<<<<<<<< HEAD:migrations/versions/1a8224881521_.py
=======
<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
=======
>>>>>>> 067e912 (This is dumb)

    if environment == "production":
        op.execute(f"ALTER TABLE reviews SET SCHEMA {SCHEMA};")


<<<<<<< HEAD
========
>>>>>>>> 761b1e0 (readme push):migrations/versions/1bd787ee40cf_.py
=======
>>>>>>> ec7cf82 (This is dumb):migrations/versions/1a8224881521_.py
>>>>>>> 067e912 (This is dumb)
    op.create_table('wishlist_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
<<<<<<< HEAD
<<<<<<<< HEAD:migrations/versions/1a8224881521_.py

    if environment == "production":
        op.execute(f"ALTER TABLE wishlist_details SET SCHEMA {SCHEMA};")
========
>>>>>>>> 761b1e0 (readme push):migrations/versions/1bd787ee40cf_.py
=======
<<<<<<< HEAD:migrations/versions/6506cb7e81a2_.py
=======

    if environment == "production":
        op.execute(f"ALTER TABLE wishlist_details SET SCHEMA {SCHEMA};")
>>>>>>> ec7cf82 (This is dumb):migrations/versions/1a8224881521_.py
>>>>>>> 067e912 (This is dumb)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wishlist_details')
    op.drop_table('reviews')
    op.drop_table('product_images')
    op.drop_table('order_products')
    op.drop_table('cart_products')
    op.drop_table('wishlists')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('carts')
    op.drop_table('users')
    # ### end Alembic commands ###
